queue_rules:
  - name: Test
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{number}})

      {{ body }}

      # Commits
      {% for commit in commits if commit.parents|length == 1 %}
      ## {{ commit.sha }}

      {{ commit.commit_message }}
      {%- endfor %}

      ---

      {%- set _ = 0 -%}
      {%- set trails = 0 -%}
      {%- set trailers = [] -%}
      {%- for commit in commits if commit.parents|length == 1 -%}
        {%- set trails = commit.commit_message.split('\n') | select('match', '^[\\w-]+:\\s+.+$') | map('split', ': ') | list %}
        {%- set _ = trailers.extend(trails) -%}
      {%- endfor %}
      {% for key, value in trailers | unique | sort %}
      {{ key }}: {{ value }}
      {%- endfor -%}
      {%- for user in approved_reviews_by %}
      Approved-by: {{ user }}
      {%- endfor -%}
