queue_rules:
  - name: Test
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{number}})

      {{ body }}

      # Commits
      {% for commit in commits if commit.parents|length == 1 %}
      ## {{ commit.sha }}

      {{ commit.commit_message }}
      {%- endfor %}

      ---

      {%- set trailers = [] -%}
      {%- for commit in commits if commit.parents|length == 1 -%}
        {%- for line in commit.commit_message.split('\n') -%}
          {%- set line = line.strip() -%}
          {%- if line and ':' in line -%}
            {%- set line_parts = line.split(':', 1) -%}
            {%- set line_key = line_parts[0]|trim -%}
            {%- set line_value = line_parts[1]|trim -%}
            {%- if line_key and line_value and line_key[0].isupper() and ' ' not in line_key -%}
              {%- set _ = trailers.append((line_key, line_value)) -%}
            {%- endif -%}
          {%- endif -%}
        {%- endfor -%}
      {%- endfor %}
      {% for key, value in trailers | unique | sort %}
      {{ key }}: {{ value }}
      {%- endfor -%}
      {%- for user in approved_reviews_by %}
      Approved-by: {{ user }}
      {%- endfor -%}
